### ISSUE TITLE
RHS AK compatibility config prevents VOGs from working

### ISSUE THREAD

**Issue by gatordev** [toadie2k/NIArms#10]
With the RHS compatibility config loaded, the RHS AKs won't work with any VOG rifle grenades.  With the config removed, both Toadie's and RHS's rifles work normally.

**Comment by toadie2k** [comment]
Like, at all at all?

**Comment by gatordev** [comment]
Admittedly short on details due to time...

RHS rifles with RHS VOGs= no worky.
Toadie rifles with RHS VOGs= works fine
Toadie rifles with Toadie VOGs= works fine.

Once I remove the compatibility config, RHS works fine with RHS VOGs.  Load order is "HLC" first then "RHS."
