### ISSUE TITLE
RHS 4.3 added a new STANAG magazine

### ISSUE THREAD

**Issue by Blutze** [toadie2k/NIArms#107]
As a refresher, 4.3 was the update that added Jets DLC support.

We are looking at leaded, non-A1 M855. Classname for the mag is `rhs_mag_30Rnd_556x45_M855_Stanag`, ammo (not that it matters for NIArms purposes) is `rhs_ammo_556x45_M855_Ball`. This mag is missing from compatibility code, and from magswitch code for the Minimis.

This magazine is currently on top of the list in arsenals and what the weapons default to, so if your squadmates don't know what they are doing you will not be able to share ammunition with them.

I might try my hand at fixing this myself, though I have zero experience with GitHub - Do I have to download some application and/or the code, or can I just create a fork or w/e on the web interface? Compatibility is super straightforward, magswitch I'd rather centralize first and then change it only once.

**Comment by Blutze** [comment]
We're getting somewhere, but where it is I can not tell. What is certain is that I'm in over my head.

My compatibility changes (leaded mags, and adding the Mk 46 snippet that appears to be missing on GitHub) nicely compile and work. Any other files I end up being smaller than they should be and give me errors about missing functions or assets, even when I try to compile the original master branch. However, if I use the SWS AiO core file I can at least tell that my magswitch changes work.

Oh, and do we care about RHS blank ammo missing from the magswitch code?

**Comment by toadie2k** [comment]
Apologies for the slow response-  any  of the missing you could provide would be appreciated, There's a high likelihood that theirs configs I failed to commit after the last patch

**Comment by Blutze** [comment]
My master core compilate gives me errors about `XEH_preInit.sqf` and `fnc_genWeaponHolders.sqf` missing when I load it in game.

Using the SWS AiO core with my master SAW file gives an error about `hlc_wp_saw\tex\ui\gear_m249e1_ca` missing (lo and behold, that one is in fact not on the GitHub), and both Mk 46s have no inventory/arsenal icon either.
Models for Squantoon's and the M249E1 Para(Short) look complete at a glance, M249 PIP (Short/RIS) and the SF variants have top covers, basic M249E1 has reciever + top cover + barrel + carryhandle + pistol grip + frontsight.

SAW compat config has no explicit mention of the Mk 46s, which overwrite the inherited magazine list back in their original config file. Copying the line with inheritance from `hlc_saw_base` scopes them out of the arsenal, inheriting from `hlc_lmg_minimi_railed` makes them inherit 30rnd capability. Had to do `magazines = [niarmsBelts, rhsBelts, bohemiaBelts]` instead of any `+=` shenanigans, though there might be a better class somewhere down the line to inherit from.

A bunch of compat subprojects aren't on the GitHub either: ACR-RHS, AUG-ACE, FAL-ACE, FAL-RHS, G3-RHS, MP5-ACE, MP5-RHS are the ones relevant to my community's modset; can't speak for anything regarding CUP. Someone fixed the AK 103 bug and uploaded that to the SWS AK compat mod on the 19th February, but nowhere else. Uhm... you don't have any minions hooked up to that mod, right?

Couldn't hear another player's gunshot sounds today (classic symptom of different modsets), running compat files compiled from my "leaded" branch for SAW and AR15 together with the SWS AiO files (normally loaded stuff + hidden compat files) for everything else. Killing AI with M855 30rnd, M855A1 Orange 30rnd, and RHS Tracer 200rnd from Colt Carbine, Mk 46 and a random FN Minimi worked well, so the server accepted my clientside-only code (we don't officially run the compat mods).

The magazines that originally kicked off this mess:
```
rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Orange
rhs_mag_30Rnd_556x45_M855_Stanag
rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Red
rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Green
rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Yellow
rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Orange
```
Plus `rhs_mag_30Rnd_556x45_M200_Stanag`, which is only missing in the magswitch code.

Oh and about the communication delay - I don't give a damn about the Tanks DLC. But the 550s, those I am excited for.

**Comment by Blutze** [comment]
Still getting smaller files and error messages when using my compilate of the updated master. First missing asset that pops up is still the M249E1 icon, E2 and both Mk 46s are still missing theirs. Most of the models appear for a frame or two and then get hidden.

Think I'm just gonna make a fresh fork, slap on all my changes, and create a pull request. Pretty sure I'm seeing my stuff shimmering through the master issues, and they appear to work.

BTW, what's the official stance on third party uploads of the compat mods, especially custom tailored to a group's modset? Would be super handy to slap FNGs with just one mod instead of what, thirteen out of twenty or whatever it is for us.

**Comment by Blutze** [comment]
Found something else: the RHS M14 compat only adds RHS mags to the RHS gun, which it can obviously use already. They even show up twice in the config viewer. The SR-25 don't inherit magazines from the M14, so if you want them to use NIArms magazines, you need to add compat code for `class rhs_weap_sr25 : srifle_EBR_F`. Not gonna change anything myself, as I'm not entirely sure about the balancing intentions here.

**Comment by robalo** [comment]
Might be best to wait and see where we end up with magazineWells. First draft of JAM using it is in CBA already, once it's finalized it will be a lot easier to fix mag compatibility issues without needing extra separate configs.

**Comment by Blutze** [comment]
Yeah, been following that process. But then again, I already made this, so... might just use it until magwells come around. Doubt its gonna be a quick migration.

Also still waiting for the go-ahead to upload a custom compatibility compilation (including a good deal of work for 3cb compat) on the Steam Workshop. Already seen a few of them around, but feels wrong to do without official permission.
