### ISSUE TITLE
AK icon missing

### ISSUE THREAD

**Issue by AlexanderViand** [toadie2k/NIArms#11]
Originally reported by Mercenary3-8 on the [biforums](https://forums.bistudio.com/topic/190455-niarms-release-thread/?p=3019232). 

[Screenshot of error message: "Picture \hlc_wp_ak\tex\ui\gear_x_ca not found"](http://i1115.photobucket.com/albums/k554/HellGhost/Error_zpsmyttufrb.png)

**Comment by theYoursTruly** [comment]
Screenshot doesn't work anymore :(
