### ISSUE TITLE
Can MagSwitch function be optimized with addPrimaryWeaponItem?

### ISSUE THREAD

**Issue by 10Dozen** [toadie2k/NIArms#110]
Hello,

recently I was suprised by addPrimaryWeaponItem command (https://community.bistudio.com/wiki/addPrimaryWeaponItem), because it can attach/detach both magazine and UGL grenade directly to weapon.

So it's looks like there is no need to 'make love' with all player's magazines (because it's pain) at here:
https://github.com/toadie2k/NIArms/blob/6e86d8150ffbcc52c0cc419fcfee26ab18079e0e/hlc_core/functions/fnc_magSwitch.sqf#L103

And just load exact magazine type right to the weapon, then make setAmmo if necessary:
player addPrimaryWeaponItem (_magClass);
player setAmmo [primaryWeapon player, (_magAmmo)];

+ save IR/flashlight states by getting:
player isFlashlightOn _gun
player isIRLaserOn _gun

and setting
player action ["GunLightOn", player]; 
player action ["IRLaserOn", player];

Hope this helps.
Best regards, 10Dozen

**Comment by robalo** [comment]
Good tips, thanks !

**Comment by robalo** [comment]
OK, fixed ammo-eating bug.
Does anyone have any idea on how to preserve optic mode ?

**Comment by 10Dozen** [comment]
@robalo didn't find any way to handle optics and zeroing (even RHS rifles loose zeroing/mode on attach/detach front handle). MagazineProxy is the only way :D
