### ISSUE TITLE
MagSwitch.sqf: Possible issue on addWeaponItem

### ISSUE THREAD

**Issue by 10Dozen** [toadie2k/NIArms#116]
Hello,

I previously suggested some changes in MagSwitch function (at [#110](https://github.com/toadie2k/NIArms/issues/110)), but it has some bad consequences =)

https://github.com/toadie2k/NIArms/blob/38810ab80a2ed3e944dc92866390067fe557e785/hlc_core/functions/fnc_magSwitch.sqf#L81-L83

I was playing with similar feature (mag switch) and found that using addWeaponItem and addPrimaryWeaponItem comands leads to next incorrect behaviour:

At line 81) Weapon will be removed
At line 82) New weapon added; **and 1 max.loaded compatible magazine consumed/loaded to new gun automatically** (as like it always happens in Arma)
At line 83) addWeaponItem changes currently loaded magazine to magazine from function input

As result: 1 magazine lost to space-time void =D

To fix it, i guess, auto-loaded magazine should be get inside swap sequence, e.g.:
After line 82) Get currently loaded magazine (autoloaded) by  `[primaryWeaponMagazine player select 0, player ammo (primaryWeapon player)]`
After line 83) Re-add autoloaded magazine. 

Tried to fix by myself here:
https://github.com/10Dozen/dzn_CUP_MagazineSwitch/blob/89e8f6c5d99a47417f62409ce666d78966f1f96b/Source/functions/fn_handleReload.sqf#L54-L74

Hope this helps.
Best regards, 10Dozen

**Comment by robalo** [comment]
Thanks. Hopefully @toadie2k gets inspiration from RHS 0.4.6 and goes mag proxy way then we could ditch this script entirely :)

**Comment by 10Dozen** [comment]
There are talks about vanilla proxy mags coming, so don't mess with RHS (they are already not compatible with vanilla rifles/mags) =3

**Comment by toadie2k** [comment]
@robalo definitely will be using. I can't say whether it'll entirely do away with the necessity for the switch script, that'll depend if the current issues with the proxy system get resolved, but at the very least the use case scale for the script probably will be significantly diminished.

**Comment by toadie2k** [comment]
As an update to previous: In conjunction with the magazinewells system (haven't figured it out yet which is impinging which to cause the behaviour)- reloading new magazines on weapons with secondary muzzles is destroying the round in the second muzzle and auto-loading a fresh round. Result over a few mag dumps is no GL rounds. 
Caught a video of the behaviour here 
https://youtu.be/BpS2qDbcDyk
The commit that you could test against,unfortunately is still uploading right now so I donn't have the code for compare and contrast here as of this moment, but the only meaningful functional difference between the two is that the HK416s use MagazineWells and the SG550s do not.

**Comment by robalo** [comment]
I'll try to debug this ASAP.
@toadie2k the video is cropped, not clear if the 550s are behaving correctly or not. Anyway I will test myself hopefully really soon. My guess is the bug affects all and was already pointed out bu 10Dozen.
@10Dozen your fix looks good, only minor issue I see is you can't guarantee the mags will go back into the same container as before they got auto-loaded. Like, not sure if it's the case, but weapon pulls mag from vest and adds it back into the backpack. Happens with some mag repacking mods too and I find that quite annoying. Might need to revert to the previous code which saved then emptied all containers and re-filled them after.

**Comment by robalo** [comment]
Referenced wrong issue in my latest commit, which fixes the ammo eating bug. So, fixed.
