### ISSUE TITLE
.300 BLK Suppressor appearing before no suppressor

### ISSUE THREAD

**Issue by worldofrandom** [toadie2k/NIArms#118]
Hi,

It seems like the .300 Blackout suppressor is listed before the no suppressor option on most 6.5mm/7.62mm guns, so when I modify loadouts I have to continually switch the unit to have no suppressor. It's really a minor issue but it does get a little annoying after a while.

**Comment by Blutze** [comment]
Seems to be an issue with alphabetical sorting and the leading period on the new name: 
![all](https://user-images.githubusercontent.com/37950828/46458822-55f71980-c7b7-11e8-8f43-3950a6ae6923.png)
Any reason the "QD" prefix was removed in https://github.com/toadie2k/NIArms/commit/fdf9897999ab071658aac5722ead4a98f7ec6c2e ?

I could easily make a PR with a fix if people throw name suggestions at me, but I'm pretty sure @toadie2k 
already has a different version of the file with support for the C96s, and committing that would risk overwriting my change. Honestly... I think it would be a good idea to not add any code for Johnsons/SCARs/XM29s to the project until after the C96s are on Steam and we had a week or two to fully update the GitHub and fix all the small little bugs floating around. Gitting should make this a non-issue, but it wouldn't be the first time neat additions to the core file get killed by a later commit. Don't ask me what happened to #74, I never used GitHub to any relevant degree.

Eh, I'm rambling. Everything's fine in the ACE Arsenal btw.

**Comment by toadie2k** [comment]
AFAIK, no, no reason the QD prefix was removed.
Also, go ahead with that PR - I keep the new content running self-sufficient prior to launch, so it shouldn't be an issue. Also agreed with prioritising for commits- though in regards to #74 as far as I can tell the lines are still in, so, question mark?

**Comment by Blutze** [comment]
Commits are in: https://github.com/toadie2k/NIArms/compare/master...Blutze:blutze-bugfixes

Just gotta find out WTF is happening with that MP5 file. The webclient complained about mixed line endings when I opened it, and then just automatically changed all of them. Not great.
