### ISSUE TITLE
HLC Frontgrips

### ISSUE THREAD

**Issue by Blutze** [toadie2k/NIArms#120]
Not sure if you wanna release the grips this weekend or if they are supposed to stay hidden until finished.

As it stands, they are missing a few tweaks if 'm not completely misreading the code:
- As per the RHS system you are keeping commonality with, grips are supposed to improve handling by setting `inertia = -0.2` on the main class. Yours just inherit the increased inertia from vanilla bipods via the UTG Shooter's.
- Going by your other weapon attachments, you seem to go for the ACE weight matching the actual real life item's weight. In the case of the Magpul AFG, [their site](https://www.magpul.com/products/afg-2) has it on 2.53 ounces, which would be `mass = 1.58125` on the internal `ItemInfo` class. Can't find anything on the vert for now, but I would expect it to be very similar.
- You currently have RHS's AFG description on both. Vert should be `"Vertical Grips aid in the maneuverability of the firearm, since the natural angle of a person's outstretched hand is more oriented to grasping objects at a vertical angle, rather than a horizontal one perpendicular to the body"`.

**Comment by toadie2k** [comment]
Yeah, they're very much still work in progress. At this point really they're in there so I have something to work with on implementation that's not RHS-dependent than anything else, so they will be commented out for the release.
