### ISSUE TITLE
Requesting Permission: Custom Compatibility Compilation on SWS

### ISSUE THREAD

**Issue by Blutze** [toadie2k/NIArms#128]
The group I am playing with is simultaneously running not all mods NIArms offers compatibility with, AND others it doesn't. We are also always fighting to keep our modset relatively lean, so we are avoiding mods that require multiple separate subscriptions on the Steam Workshop. And lastly, we are exclusively using the SWS for mod hosting, because it apparently makes controlling the server's mod significantly easier and because it obviously removes a number of idiot traps compared to, say, Arma3Sync or Armaholic. Which is important for a community that tries to be as open as we do.

Consequently, I have put together a batch of all the official NIArms compat .pbos we need, edited some of them to include our other mods into the system, and then went on to add a number of fixes to those mods (as well as some fixes that I have contributed here, but aren't on the Workshop yet). There are issues fixed like:
- RHS magazines that had the wrong ammo type
- RHS belt linking and barrel swapping on things new in 0.4.8 (most of these have been fixed in ACE now)
- 3cb small arms magazines not available in the arsenal
- 3cb vehicle and tripod mounted FN MAGs using compatible magazines

So far, I have simply used that myself and given it to friends. That has however led to incidents of people picking up my guns and being unable to reload them, and to me having to maintain separate loadouts for sharing with newcomers. And those tripod mounted guns are being unreliable because (I think) ownership of the "vehicle" is being transferred to a client that isn't running my mod, so they suddenly stop accepting any mags it adds.

I have asked before, but it has always gotten buried in other topics discussed in the same threads, so here I am making a ticket dedicated to it: I would like to publish this mod on the Steam Workshop, so I can get it added to my group's official modset. It will include some pbo files straight from other NIArms uploads, and some based on the code here on GitHub but edited and compiled by me. There will be a clear list of the origins of the files.

The licences you are running, as far as I can wrap my head around the legalese, seem to allow mods like this, and there is precedent in others of this kind floating around - but the ArmA modding community and the SWS always had a weird relationship, and I figured I'd rather get permission. So... may I?

**Comment by jonpas** [comment]
Even with permissive license, it's always great to see people ask, kudos to you!

**Comment by Blutze** [comment]
How I imagine @toadie2k looking at me these last two weeks:
![that](https://user-images.githubusercontent.com/37950828/54356631-5d6ef880-465c-11e9-9ac3-1ac60999926e.png)

**Comment by toadie2k** [comment]
Yeah, totally, down to the glasses.  Also more relatedly,IMO your're pretty good to go. I'd just add that at least some of what you're doing is deprecated by CBA JAM/Magwells, but I guess in the intervening moments that that's NOT in the public release it's good to have options.

**Comment by toadie2k** [comment]
Also I'm stealing that image.

**Comment by Blutze** [comment]
T'is up: https://steamcommunity.com/sharedfiles/filedetails/?id=1360769036

You... you image-stealer you.

(Also, I never watched that movie. Guess I'm gonna have to now.)
