### ISSUE TITLE
Adjusting fire selector sounds

### ISSUE THREAD

**Issue by Cyruz143** [toadie2k/NIArms#2]
The `changeFiremodeSound` on the majority (if not all of you weapons) were implemented before BI reviewed and updated the values to stop them being heard from 20m away.

The mk20 runs 
`changeFiremodeSound[] = {"A3\Sounds_F\arsenal\weapons\Rifles\Mk20\firemode_Mk20",0.251189,1,5};`

vs the AK 
`changeFiremodeSound[] = {"hlc_wp_ak\snd\ak_selector",1,1,20};`

Side note: If you put the configs online, we could PR and fix stuff for you!

**Comment by toadie2k** [comment]
Certainly considering it. Would want peeps  I can hold some confidence in to oversee it, watch this space.
