### ISSUE TITLE
RPK missed inventory image

### ISSUE THREAD

**Issue by FlyMakerBR** [toadie2k/NIArms#22]
http://image.prntscr.com/image/51cd34a9f91544718a7909564c8d3c8a.png

**Comment by theYoursTruly** [comment]
Can you correct the link please?

**Comment by FlyMakerBR** [comment]
Link updated

**Comment by toadie2k** [comment]
Closed as of ea2fc66d0a2f7e2bb2c1c25278b2d5dd4fd1523a commit
