### ISSUE TITLE
1P29 range finder missed horizontal base line

### ISSUE THREAD

**Issue by FlyMakerBR** [toadie2k/NIArms#23]
Real 1P29 - http://zenphotos.net/file/Online/SVD/Optics/1P29_ReticuleSky.JPG
NIArms 1P29 - http://image.prntscr.com/image/63be0c43e40e494eaff6de0745cc0d1f.png

**Comment by toadie2k** [comment]
believe it or ot, the line's actually there, it just seems to get downsampled out at anything lower than 1080p.
