### ISSUE TITLE
AWM pack lacks ACE tracer compatibility

### ISSUE THREAD

**Issue by Wiesore** [toadie2k/NIArms#35]
When using tracers with AWM rifles, they look like vanilla tracers, not the ACE tracers. 

I tried G36's just to check if it's a problem on my end, and their tracers work like expected.

**Comment by theYoursTruly** [comment]
AWC config has 3 _CfgAmmo_ entires with _model_ defined. They all inherit from _B_556x45_Ball_ which by default has yellow tracer. We can remove _model_ entry from all of them. But _HLC_300WM_Tracer_ has red tracer so we should either accept that it is yellow now, or change its' parent class to _B_556x45_Ball_Tracer_Red_.

Changes in **config.cpp**:
- remove line 183
- remove line 225
- remove line 267
- (optional) add `class B_556x45_Ball_Tracer_Red;` after line 166 and replace line 212 with 
`class HLC_300WM_Tracer : B_556x45_Ball_Tracer_Red {`

**Comment by theYoursTruly** [comment]
Fixed by dbdbffc9461dd497c0b9c2033bbb2d01b6df77ec
