### ISSUE TITLE
Error: creating weapon UGL_F with scope=private

### ISSUE THREAD

**Issue by Azazelwho** [toadie2k/NIArms#49]
Hi!

I get this error at launch
16:24:30 Warning Message: Error: creating weapon UGL_F with scope=private

I have the all in one package from steam http://steamcommunity.com/workshop/filedetails/?id=665702172

Thanks!

**Comment by robalo** [comment]
duplicate of #41

**Comment by Azazelwho** [comment]
Oh yes, but how to fix this?
I have to open all config.bin and made change one by one or it will be fixed with the next update?

Thanks

**Comment by robalo** [comment]
Fixed in source so either wait for next update or fix it yourself. Totally up to you.

**Comment by Azazelwho** [comment]
Thanks! :)
