### ISSUE TITLE
AWM

### ISSUE THREAD

**Issue by madpat3** [toadie2k/NIArms#56]
can't shoot the weapon (all versions)

when i select it in arsenal i get this error: [BIS_fnc_baseWeapon] class'%ALL' not found in cfgWeapons

by the way, the weapon is listed under assault rifles, not under sniper rifles (eden-editor).

**Comment by theYoursTruly** [comment]
I can't reproduce it. What mods are you running? Did you try with just @NIArsenal and @CBA_A3?

**Comment by madpat3** [comment]
yes, only with cba and niarms. but i tried kesha's Weapon Eventhandler Framework https://forums.bistudio.com/topic/182380-weapon-eventhandler-framework/

after unloading the mod, the rifle still shows the anim when reloading and it doesn't shoot.

(cannot get rid of the anim)

**Comment by theYoursTruly** [comment]
I have no such problems on my side using Core v1.1 and AWM 1.3
Even if I add this Weapon EventHandler Framework it still works.
Can you send me your RPT file?

**Comment by madpat3** [comment]
http://pastebin.com/FqyGFjE7

**Comment by madpat3** [comment]
omg,
my bad.
i had the old version of core loaded (v.1.0.5)
with the latest version it works just fine.
again, sorry!!!

**Comment by theYoursTruly** [comment]
I'm glad everything works now :)
