### ISSUE TITLE
hlc_75Rnd_762x39_m_rpk not in __762x39 MAGS macro

### ISSUE THREAD

**Issue by Cyruz143** [toadie2k/NIArms#61]
`hlc_75Rnd_762x39_m_rpk` have been removed from `__762x39_MAGS` but the class is still defined here: https://github.com/toadie2k/NIArms/blob/0d4e115cc05cd1cfb16054ca4c08f0a2f553d94d/hlc_wp_ak/config.cpp#L474

Unsure if it's forgotten or is going to be removed.

**Comment by robalo** [comment]
Was never defined in there, must've missed it.
