### ISSUE TITLE
Make special NIArms magazines compatible with vanilla weapons

### ISSUE THREAD

**Issue by jonpas** [toadie2k/NIArms#62]
For example all the special 5.56 magazines that are in NIArms are not compatible with 5.56 guns. However NIArms guns can use both NIArms magazines and the vanilla magazines. Would be nice if the vanilla ones could get the compatibility as well, so we could share more ammo (and it would be realistic too).

The subConfig that gets around the `+=` "bug" might help?

**Comment by toadie2k** [comment]
I like this idea, I'll see what I can do about it

**Comment by ravmustang** [comment]
New config needed for each vanilla weapon adding in new magazine into the config entry:
magazines[] = {};

It is possible and has been implemented by me for other types of magazines and weapons.

**Comment by Whigital** [comment]
We've done something similar to get compatibility across different weapons in our modset:

https://github.com/Whigital/ff7_compats/blob/master/ff7_compat_hlc_rhs_ace/CfgWeapons.hpp#L3

Some of the configs are really sloppy, so there might be some needed cleaning, but it works :)

**Comment by Whigital** [comment]
Looks like there was a commit back in april that added HLC 5.56 STANAG compatibility to vanilla guns:

https://github.com/toadie2k/NIArms/commit/94cb40bb9e0284baa84a9f486c833fa0f38bf9b0#diff-a4341ff7e28b413863c2ffc79783c7dbR3524

**Comment by robalo** [comment]
Yep, fixed with 94cb40b
