### ISSUE TITLE
Mag Switch incompatibilities

### ISSUE THREAD

**Issue by jonpas** [toadie2k/NIArms#65]
Ahoy, as much as I like the mag switch you implemented in NIArms, there are a few problems I'd be worried about, especially if it's not going to be an optional, there are problems with compatibility with ACE overheating (due do magazine IDs and non-persistent weapons), zeroing resetting on mag switch... etc. Basically the implementation is rather hacky due do direct manipulation of inventory (weapon).

Any insight into the plans for that, making it optional and similar? Last thing I'd want for NIArms is a script, which basically makes some other mod's feature irrelevant, mixed with all the content.

As an alternative I'd recommend rather making it a framework and have it in CBA (if they agree,) so we could implement hooks for it and make it compatible with other systems that might rely on weapons if that system must really be non-optional.

I also know this doesn't really fit on this issue tracker, but couldn't reach you guys on Slack. :)
Also not trying to say your work is by any means bad!

**Comment by toadie2k** [comment]
I'll let Robalo speak for his goals and the technicality of it, but the concept hits some of the hard walls of arma's soft-coded weapon functionality. So yeah, there's some unavoidable side-effects with regards to, like you mentioned, ACE overheating (and thermals in general).
Now as regards to a solution, I'd like to still make the switching the default as without ACE the only real annoyances come from firemode and zero,  so maybe out of the box Core could come with a disabling PBO? I dunno. I'm taking suggestions on solutions here.

**Comment by robalo** [comment]
Oh hey, so yeah, with ACE I see 2 options:
1. detect ACE and disable this function automatically
2. detect ACE and fix any issues using available ACE functionality if possible

**Comment by jonpas** [comment]
That will not fix zeroing and thermals being reset though. Neither of which can be set back with SQF at the moment. That is why I would prefer if we could simply disable this functionality, I still see valid uses for it, making it optional to the user would be the best way in my opinion, at least until proper solution is made/found.

**Comment by robalo** [comment]
About zeroing, I thought ACE had a function to set it. In vanilla we can read it but not set it.
Same for vision modes, no command to set it.
Fire mode should be preserved. You mentioned that in initial post.

**Comment by jonpas** [comment]
AFAIK we do not, as it is not possible to do it via SQF. Yeah, basically as you said, some things won't be able to be set back at all either way. Which is sad.

> Fire mode should be preserved. You mentioned that in initial post.

Toadie mentioned that. 😆

**Comment by jonpas** [comment]
Why not add a CBA Settings for it @robalo ? That would solve the issue as a whole, and not just if ACE3 is present. Who doesn't care can leave it enabled, who wants other features can disable it.

**Comment by jonpas** [comment]
I'd be willing to make a PR for that setting if you agree.

**Comment by robalo** [comment]
Sounds good to me !
