### ISSUE TITLE
Error starting with NIarms

### ISSUE THREAD

**Issue by KPGaming** [toadie2k/NIArms#67]
on joining my server i get HLC_compact_ace3_ar15 requires addon ace_common ,
don't know what I am missing , 
I tried using CBA3 and asdg_jr_u I get the same error on both . 
When I close the message box all is ok , I join and can view and buy from the trader.

**Comment by robalo** [comment]
Don't use ACE3 compatibility addons if you're not using ACE3.
Also don't use the standalone ASDG_JR mod, use CBA3 instead.
