### ISSUE TITLE
Sound files not found

### ISSUE THREAD

**Issue by jonpas** [toadie2k/NIArms#8]
SG510 v1.1
```
14:12:58 Sound: Error: File: \hlc_wp_sigamt\snd\amtswitch.wss not found !!!
```
AR15 v1.7
```
15:20:52 Sound: Error: File: \hlc_wp_ar15\snd\ar15_selector.wss not found !!!
```

**Comment by toadie2k** [comment]
Also,for my own reference-

> Sound: Error: Multi-stream: Load failed, stream hlc_wp_g36\snd\soundshaders\g36k_forrest.wss not found !!!
Check G36K soundshaders.
