### ISSUE TITLE
hlc_50rnd_762x51_M_FAL has (ammo) count 20

### ISSUE THREAD

**Issue by derbismarck** [toadie2k/NIArms#80]
Source code here in `hlc_WP_FAL` doesn't reflect this issue, however the unpacked release version downloaded from the NIArms website does. (`NIArms_AllinOne_V8.rar`)

```
class hlc_50rnd_762x51_M_FAL: hlc_20Rnd_762x51_B_fal
{
	author = "Toadie, Spartan0536";
	mass = 17;
	descriptionshort = "Caliber: 7.62x51mm NATO M80A1-M62A1<br />Type: EPFMJ/Incendiary Tracer<br />Rounds: 50";
	displayname = "X-FAL Magazine (EPR-Tracer) 50rnd 7.62mm";
	model = "\hlc_wp_FAL\mesh\magazine\magazine.p3d";
	initspeed = 908.4;
	lastroundstracer = 3;
	picture = "\hlc_core\tex\ui\ammo\m_faltracer_ca.paa";
	scope = 2;
	tracersevery = 4;
	displaynameshort = "EPR/Tracer";
};
```

As you can see, `hlc_50rnd_762x51_M_FAL` inherits `count` from the 20 round magazine without setting the value to 50 (which it should). This means that, in-game, the magazine contains twenty rounds rather than fifty.

**Comment by kOepi123** [comment]
hmm, I stumbled over a few different stages of progress on the master repo, missing files etc.
Dont really understand what I am doing wrong or how that is supposed to work. grrrr
