### ISSUE TITLE
Question Regarding Independent Forks

### ISSUE THREAD

**Issue by Snak3Doc** [toadie2k/NIArms#85]
Hi Toadie

Few questions regarding independent forks, I was wondering if its ok to make a fork for the purpose of making a cut-down version for a unit? (it would only be released through a private repo)

Specifically, I want to run a cut-down set of weapon .pbos with some edits to configs to scope out some variants of weapons that we don't use, and removing the mag switch function because of how it interferes with ace.

Thanks for all the awesome weapons :)

**Comment by kOepi123** [comment]
as the matter of fact I am working on a very similar patch right now, but in regards to the BI wepons, so I have a clean virtual arsenal.
That would not need to edit the pbos and have everyone the same unchanged pbo files.

**Comment by Snak3Doc** [comment]
Yea i considered a patch for the scoping scoping side but wanted to save on some megabytes as well eg ( Australian internet ftw) and i want to do it on Git so I can track updates easily, just though I'd ask permission first even though it is Git

**Comment by kOepi123** [comment]
it is your own fork. what you want to do exactly is making a branch for your own fork, that will not affect the NiArms original repository, only your own fork.

**Comment by toadie2k** [comment]
Echoing Koepi, you're safe to fork.

**Comment by Snak3Doc** [comment]
Hi I, just finished uni and got round to looking at making a cutdown version, could anyone explain whats up with the scoping in the configs for niarms, in relation
a)all the "scopeArsenal = 0;" but they show in the arsenal?
b)what is "scope = public;" and "scope = protected;" ?

If theirs a biwiki page im missing a link to that would be fine.

**Comment by kOepi123** [comment]
I dont understand a)
b) scope = 0; scope = private is basically the same appearance as scopearsenal = 0
Only difference is that potentional child configs might produces errors, on the other hand
you can delete it out of the modpack and make it lighter.

**Comment by jonpas** [comment]
@Snak3Doc https://community.bistudio.com/wiki/Arma_3_Characters_And_Gear_Encoding_Guide#Character_configuration in the "sample character config".

**Comment by Snak3Doc** [comment]
Thanks for the info guys (had all my time stolen by work and uni, so ive only just got back to this). Im having some issues trying to compile my custom version, even when using an unedited version stright from git, i get this with every gun (https://puu.sh/zhIED/df6b4de82e.png) when compiling it with addon builder. not realy sure what im doing wrong, as ive made my own mods, and compiled unreleased fix's ect from ace3 git before.
