### ISSUE TITLE
Kern 4x24 uses mil adjustment instead of distance based adjustment when used with ACE

### ISSUE THREAD

**Issue by nic547** [toadie2k/NIArms#91]
The Kern 4x24 for the Stgw. 57 family of rifles has the distance written on them and not mils. With ACE, the mil system is used instead. IMHO this makes the scope unnecessary hard and slow to use (and it's unrealistic too!).
I would like to see it work like it would in real life. 

[source](https://www.kern-aarau.ch/fileadmin/user_upload/Aldo/Wehrtechnik/Zielfernrohr_4x24_d.pdf)

**Comment by toadie2k** [comment]
Fixed as part of current release, commit coming up.

**Comment by nic547** [comment]
Nice to hear, thanks for your great work!
