### ISSUE TITLE
AKS74 (GL) issues

### ISSUE THREAD

**Issue by s4098055** [toadie2k/NIArms#92]
G'day all,

There's some weirdness going on with the AKS74 (GL).

- The AKS74 (GL)'s GP30 disappears when it is loaded with RPK magazines (both 45- and 60-round variants). Oddly enough, the hand animations remain correct, it just can't be seen. Probably warrants a dive into the P3D.
- A grenade fired from the launcher while the weapon is in this state will travel at 90 degrees to the right of the actual muzzle direction.
- Upon reloading the GP30, the weapon will revert back to the 30-round model (with a 30-round magazine loaded, if available). The launcher will function as expected after this.

Reproduction achieved via the virtual arsenal - give yourself the AKS74 (GL variant), at least one RPK magazine and some VOGs for shits and giggles. Load an RPK magazine to start. The GP30 will disappear. Fire a grenade from the launcher and wonder where it went. Reload the launcher, et voila! 30-round magazine!

**Comment by s4098055** [comment]
The third issue (reversion to 30-round model on GP reload) might require its own ticket, as it seems to be reproducible with all GL AKs. Let me know if so.

**Comment by toadie2k** [comment]
Confirmed, third should be it's own ticket.

**Comment by s4098055** [comment]
Thanks, [done](https://github.com/toadie2k/NIArms/issues/94).
