### ISSUE TITLE
Colt Carbine (GL) throws texture and muzzle flash errors upon loading X-15 magazine

### ISSUE THREAD

**Issue by s4098055** [toadie2k/NIArms#93]
G'day all,

The Colt Carbine (GL) will pop up an error when loaded with the X-15 magazine.

`13:34:44 Warning Message: Cannot load texture xmag_uvtemplate.paa.`

The magazine itself is untextured (white) ingame.

In addition, the muzzle flash becomes visible and doesn't hide when the weapon is fired (might be similar to [this](https://github.com/toadie2k/NIArms/issues/86)).

Repro is easy - open arsenal, give yourself the Colt Carbine (GL) and an X-15 magazine, load aforementioned magazine.

**Comment by toadie2k** [comment]
I may or may not have actually fixed this in a git push and not put a mention, will double check. If not, there's an upcoming commit I can certify does fix.
